name: app_planetarium
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.0-190.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_scene:
    path: ../
  flutter_scene_importer:
    path: ../importer
  native_assets_cli: ">=0.13.0 <0.14.0"
  vector_math: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    # Imported models.
    - build/models/
